### ISSUE TITLE
Background image?

### ISSUE THREAD

**Issue by piton182** [LapshinIV/AvaElm#2]
This article might help in doing it super proper https://css-tricks.com/perfect-full-page-background-image/

Just an idea for the background image: https://www.google.se/search?q=background+images+for+website&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiM0YSfkbfLAhWBC5oKHaABCC4Q_AUIBygB&biw=1440&bih=729#tbm=isch&q=background+images+for+website+matrix

**Comment by LapshinIV** [comment]
Hi! please check my changes for this task, i think it's not bad :)
